In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Matrix operation with `numpy`

## 1. definition

In [2]:
dim = 5
rows = 4
cols = 5

## 2. Vector

In [3]:
v1 = np.array([1,2,3,4,5.])
v2 = np.random.random(5)
print ('v1: ', v1, '\nv2: ', v2)

v1:  [1. 2. 3. 4. 5.] 
v2:  [0.53504903 0.57477475 0.97010861 0.17700236 0.67030326]


## 2.1 Element-wise +, -, *, /

In [4]:
v = v1 + v2
v

array([1.53504903, 2.57477475, 3.97010861, 4.17700236, 5.67030326])

In [5]:
v = v1 * v2
v

array([0.53504903, 1.1495495 , 2.91032582, 0.70800946, 3.35151631])

In [6]:
v = v1 / v2
v

array([ 1.86898759,  3.47962399,  3.09243726, 22.59856811,  7.45931025])

### 2.2 dot product

In [7]:
dp = np.dot(v1, v2)
dp

8.654450122630317

In [8]:
dot_sum = 0
for i in range (v1.shape[0]):
    dot_sum += v1[i]*v2[i]
print ('Dot product of two vectors: ', dot_sum, dp, ' and difference: ', dot_sum - dp)

Dot product of two vectors:  8.654450122630317 8.654450122630317  and difference:  0.0


## 3. Matrix

In [9]:
mat1 = np.random.random((rows,cols)) # random in [0, 1)
mat1

array([[0.42585582, 0.50638409, 0.876621  , 0.36736175, 0.056552  ],
       [0.94128669, 0.65590733, 0.58614308, 0.83912628, 0.9563282 ],
       [0.49857033, 0.86719185, 0.80088826, 0.10555436, 0.25831567],
       [0.71235736, 0.5795033 , 0.41276296, 0.93181183, 0.39628132]])

In [10]:
mat1.shape, mat1.dtype

((4, 5), dtype('float64'))

In [11]:
mat2 = np.random.random((rows, cols))
mat2

array([[0.67443789, 0.38734264, 0.07762864, 0.07110945, 0.18716626],
       [0.67881515, 0.6117804 , 0.98800567, 0.88883466, 0.66128839],
       [0.78996521, 0.6318086 , 0.81591363, 0.71071962, 0.34471573],
       [0.92674294, 0.22213029, 0.42224431, 0.03420667, 0.93353253]])

### 3.1 Element-wise Matrix operations: +, -, *, /

In [12]:
m = mat1 + mat2
m

array([[1.10029371, 0.89372673, 0.95424964, 0.43847121, 0.24371826],
       [1.62010184, 1.26768772, 1.57414876, 1.72796094, 1.61761659],
       [1.28853554, 1.49900046, 1.61680189, 0.81627398, 0.6030314 ],
       [1.6391003 , 0.8016336 , 0.83500727, 0.9660185 , 1.32981385]])

In [13]:
m = mat1 * mat2
m

array([[0.2872133 , 0.19614415, 0.06805089, 0.02612289, 0.01058463],
       [0.63895966, 0.40127124, 0.57911269, 0.74584452, 0.63240874],
       [0.39385321, 0.54789927, 0.65345565, 0.07501956, 0.08904548],
       [0.66017216, 0.12872524, 0.17428681, 0.03187418, 0.3699415 ]])

In [14]:
m = mat1 / mat2
m

array([[ 0.63142332,  1.30732854, 11.29249501,  5.16614512,  0.30214846],
       [ 1.38666129,  1.07212871,  0.59325882,  0.94407467,  1.44615908],
       [ 0.63112947,  1.37255468,  0.98158461,  0.14851759,  0.74935854],
       [ 0.7686677 ,  2.60884409,  0.97754536, 27.24065126,  0.42449653]])

### 3.2 Matrix multiplication: @
- size constraint must be satisfied
- $ A(r,c) \times B(c, d) = C(r,d) $

In [15]:
# matrix transpose operation
mat3 = mat2.T
print('A: ', mat1.shape, 'B: ', mat3.shape)

A:  (4, 5) B:  (5, 4)


In [16]:
mat3

array([[0.67443789, 0.67881515, 0.78996521, 0.92674294],
       [0.38734264, 0.6117804 , 0.6318086 , 0.22213029],
       [0.07762864, 0.98800567, 0.81591363, 0.42224431],
       [0.07110945, 0.88883466, 0.71071962, 0.03420667],
       [0.18716626, 0.66128839, 0.34471573, 0.93353253]])

In [17]:
mm = mat1 @ mat3
mm

array([[0.58811586, 1.8289008 , 1.65218169, 0.94264969],
       [1.17306396, 2.99759686, 2.56227864, 2.18699045],
       [0.79018086, 1.92489175, 1.75927317, 1.23760336],
       [0.87738049, 2.33618276, 2.06451298, 1.36499988]])

In [18]:
mm.shape

(4, 4)

In [19]:
mat1[0], mat3[:,0]

(array([0.42585582, 0.50638409, 0.876621  , 0.36736175, 0.056552  ]),
 array([0.67443789, 0.38734264, 0.07762864, 0.07110945, 0.18716626]))

In [20]:
mm00 = mat1[0].dot(mat3[:,0])
print ('This value mm00: {} must be the same as mm[0,0]: {}'.format(mm00, mm[0,0]))

This value mm00: 0.5881158649258862 must be the same as mm[0,0]: 0.5881158649258863


In [21]:
diff = mm00 - mm[0,0]
print ('this means zeros: ', diff)

this means zeros:  -1.1102230246251565e-16


### 3.3 Matrix - Vector Multiplication

In [22]:
mat1.shape, v1.shape

((4, 5), (5,))

The dimension of $v_1$ must be $5\times1$ for the m-v multiplication

In [23]:
v5x1 = v1[:,np.newaxis]
v5x1

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])

Now we can compute the multiplication as the definition says.

In [24]:
mv_5x1 = mat1 @ v5x1
mv_5x1

array([[ 5.82069401],
       [12.14967674],
       [ 6.34941465],
       [ 8.81830679]])

- `Numpy` just do it without dimension extension. I don't recomment it if you feel confused.

In [25]:
mv1 = mat1 @ v1
mv1

array([ 5.82069401, 12.14967674,  6.34941465,  8.81830679])

Notice that the two variables `mv_5x1` and `mv1` have the same values, but different dimensions.

In [26]:
mv1.shape, mv_5x1.shape

((4,), (4, 1))

In [27]:
# simple subtraction will result in something unexpected!
mv1 - mv_5x1

array([[ 0.        ,  6.32898273,  0.52872064,  2.99761278],
       [-6.32898273,  0.        , -5.80026209, -3.33136995],
       [-0.52872064,  5.80026209,  0.        ,  2.46889214],
       [-2.99761278,  3.33136995, -2.46889214,  0.        ]])

In [28]:
# you can use squeeze
mv_5x1_sqz = mv_5x1.squeeze(axis=1)
mv_5x1_sqz

array([ 5.82069401, 12.14967674,  6.34941465,  8.81830679])

### 3.4 Matrix Decompositions

In [29]:
mat = np.random.random((4,4))
mat = mat + mat.T # make it symmetric for better understanding
mat

array([[0.98377453, 1.02724686, 0.87356395, 0.50033262],
       [1.02724686, 0.0972038 , 1.6178334 , 0.99884959],
       [0.87356395, 1.6178334 , 1.34001702, 0.94815121],
       [0.50033262, 0.99884959, 0.94815121, 0.74970232]])

#### Eigen-decomposition

In [30]:
ev, em = np.linalg.eig (mat)
ev

array([ 3.87511363, -1.14682066,  0.4095024 ,  0.03290231])

In [31]:
recon = em @ np.diag (ev) @ em.T
recon - mat

array([[2.33146835e-15, 1.55431223e-15, 2.66453526e-15, 1.44328993e-15],
       [1.55431223e-15, 8.88178420e-16, 1.11022302e-15, 7.77156117e-16],
       [2.66453526e-15, 8.88178420e-16, 2.66453526e-15, 1.33226763e-15],
       [1.44328993e-15, 7.77156117e-16, 1.33226763e-15, 8.88178420e-16]])

#### Singular Value Decomposition (SVD)

In [32]:
u, s, vt = np.linalg.svd(mat)

In [33]:
s

array([3.87511363, 1.14682066, 0.4095024 , 0.03290231])

In [34]:
recon = u @ np.diag(s) @ vt
recon - mat

array([[ 1.11022302e-15,  0.00000000e+00, -2.22044605e-16,
        -4.44089210e-16],
       [-6.88338275e-15,  2.22044605e-16,  1.77635684e-15,
         4.10782519e-15],
       [ 2.99760217e-15,  0.00000000e+00, -8.88178420e-16,
        -1.77635684e-15],
       [ 1.55431223e-15,  1.11022302e-16, -2.22044605e-16,
        -7.77156117e-16]])

SVD for a $m\times n$ matrix

In [35]:
mat43 = np.random.random((4,3))
mat43

array([[0.29856387, 0.54758804, 0.18936927],
       [0.06473684, 0.59199408, 0.61605665],
       [0.68200691, 0.01662874, 0.48875277],
       [0.96453598, 0.48466411, 0.42641855]])

In [36]:
u, s, vt = np.linalg.svd (mat43, full_matrices=False)

In [37]:
u.shape, s.shape, vt.shape

((4, 3), (3,), (3, 3))

In [38]:
recon = u @ np.diag(s) @ vt
recon - mat43

array([[ 1.66533454e-16,  4.44089210e-16,  2.77555756e-17],
       [-1.94289029e-16,  3.33066907e-16,  2.22044605e-16],
       [ 1.11022302e-16, -6.93889390e-18, -5.55111512e-17],
       [ 4.44089210e-16,  1.66533454e-16,  0.00000000e+00]])

In [39]:
u

array([[-0.35683369, -0.33065197,  0.54662544],
       [-0.40758108, -0.76001477, -0.45863378],
       [-0.45973424,  0.47301054, -0.59176398],
       [-0.70369866,  0.2988442 ,  0.37506145]])

In [40]:
# u is a unitary (or orthogonal) matrix: the columns are orthogonal to each other, and mag = 1
u.T @ u

array([[ 1.00000000e+00, -1.29230700e-16, -2.22439025e-16],
       [-1.29230700e-16,  1.00000000e+00,  6.68365100e-17],
       [-2.22439025e-16,  6.68365100e-17,  1.00000000e+00]])

In [41]:
# but this is not!
u @ u.T

array([[ 0.53546038,  0.14603816, -0.31582644,  0.3573081 ],
       [ 0.14603816,  0.95408972,  0.09928693, -0.11232759],
       [-0.31582644,  0.09928693,  0.78527915,  0.24292297],
       [ 0.3573081 , -0.11232759,  0.24292297,  0.72517075]])

In [42]:
# vt is a unitary and square matrix
vt.T @ vt

array([[ 1.00000000e+00, -1.99243502e-16, -2.30716939e-16],
       [-1.99243502e-16,  1.00000000e+00,  2.62264783e-17],
       [-2.30716939e-16,  2.62264783e-17,  1.00000000e+00]])

In [43]:
# so this too results in id. matrix
vt @ vt.T

array([[ 1.00000000e+00,  4.12115070e-17, -1.48279246e-16],
       [ 4.12115070e-17,  1.00000000e+00, -1.81807205e-17],
       [-1.48279246e-16, -1.81807205e-17,  1.00000000e+00]])

In [44]:
for i in range(vt.shape[0]):
    print ('mag: ', np.linalg.norm(vt[i]))

mag:  1.0
mag:  1.0000000000000002
mag:  1.0000000000000002


In [45]:
for i in range(vt.T.shape[0]):
    print ('mag: ', np.linalg.norm(vt.T[i]))

mag:  1.0000000000000002
mag:  1.0000000000000002
mag:  1.0


#### Determinant

In [46]:
np.linalg.det(vt), np.linalg.det(vt.T)

(-1.0000000000000007, -1.0000000000000007)

#### Inverse of non-singular square matrix

In [47]:
np.linalg.det( mat ) 

-0.059877382354025815

In [48]:
inv = np.linalg.inv (mat)
ii = inv @ mat
np.linalg.det(ii) # must be 1 since ii is identity matrix

0.9999999999999998

In [49]:
ii

array([[ 1.00000000e+00, -8.77876586e-16, -2.58865495e-15,
        -1.92605416e-15],
       [ 3.18262548e-16,  1.00000000e+00,  5.85980139e-16,
         2.98735010e-16],
       [ 7.49758956e-16, -6.60470448e-16,  1.00000000e+00,
         1.01139864e-15],
       [-3.27276918e-16, -4.88818169e-16, -1.68093115e-15,
         1.00000000e+00]])

# END