In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Matrix operation with `numpy`

## 1. definition

In [2]:
dim = 5
rows = 4
cols = 5

## 2. Vector

In [12]:
v1 = np.array([1,2,3,4,5.])
v2 = np.random.random(5)
print ('v1: ', v1, '\nv2: ', v2)

v1:  [1. 2. 3. 4. 5.] 
v2:  [0.58154765 0.64397353 0.18150711 0.23752809 0.95577835]


## 2.1 Element-wise +, -, *, /

In [13]:
v = v1 + v2
v

array([1.58154765, 2.64397353, 3.18150711, 4.23752809, 5.95577835])

In [15]:
v = v1 * v2
v

array([0.58154765, 1.28794706, 0.54452133, 0.95011238, 4.77889174])

In [16]:
v = v1 / v2
v

array([ 1.71954956,  3.10571771, 16.52827812, 16.84011317,  5.23133843])

### 2.2 dot product

In [43]:
dp = np.dot(v1, v2)
dp

8.143020153942452

In [45]:
dot_sum = 0
for i in range (v1.shape[0]):
    dot_sum += v1[i]*v2[i]
print ('Dot product of two vectors: ', dot_sum, dp, ' and difference: ', dot_sum - dp)

Dot product of two vectors:  8.143020153942452 8.143020153942452  and difference:  0.0


## 3. Matrix

In [7]:
mat1 = np.random.random((rows,cols)) # random in [0, 1)
mat1

array([[0.63618784, 0.5729108 , 0.12698371, 0.75403451, 0.51292941],
       [0.73995851, 0.76302034, 0.04781376, 0.60116906, 0.47542164],
       [0.09566303, 0.60235683, 0.00413574, 0.10844392, 0.02509737],
       [0.03470299, 0.2661915 , 0.44971789, 0.26195658, 0.10764769]])

In [25]:
mat1.shape, mat1.dtype

((4, 5), dtype('float64'))

In [8]:
mat2 = np.random.random((rows, cols))
mat2

array([[0.00578983, 0.51070896, 0.60682532, 0.38014173, 0.7881372 ],
       [0.25014527, 0.08218338, 0.78042585, 0.68079187, 0.32073964],
       [0.96314436, 0.35094065, 0.17994085, 0.52446271, 0.96251401],
       [0.88965735, 0.8589889 , 0.51257492, 0.57069585, 0.48683036]])

### 3.1 Element-wise Matrix operations: +, -, *, /

In [18]:
m = mat1 + mat2
m

array([[0.64197767, 1.08361976, 0.73380902, 1.13417624, 1.30106661],
       [0.99010378, 0.84520373, 0.82823961, 1.28196093, 0.79616128],
       [1.05880739, 0.95329748, 0.18407659, 0.63290663, 0.98761138],
       [0.92436034, 1.1251804 , 0.9622928 , 0.83265243, 0.59447805]])

In [23]:
m = mat1 * mat2
m

array([[0.00368342, 0.29259068, 0.07705693, 0.28663998, 0.40425875],
       [0.18509712, 0.06270759, 0.03731509, 0.40927101, 0.15248657],
       [0.09213731, 0.2113915 , 0.00074419, 0.05687479, 0.02415657],
       [0.03087377, 0.22865555, 0.23051411, 0.14949753, 0.05240617]])

In [24]:
m = mat1 / mat2
m

array([[1.09880264e+02, 1.12179507e+00, 2.09259075e-01, 1.98356153e+00,
        6.50812332e-01],
       [2.95811513e+00, 9.28436268e+00, 6.12662380e-02, 8.83043827e-01,
        1.48226656e+00],
       [9.93236686e-02, 1.71640656e+00, 2.29839086e-02, 2.06771465e-01,
        2.60748075e-02],
       [3.90071395e-02, 3.09889341e-01, 8.77370060e-01, 4.59012582e-01,
        2.21119520e-01]])

### 3.2 Matrix multiplication: @
- size constraint must be satisfied
- $ A(r,c) \times B(c, d) = C(r,d) $

In [127]:
# matrix transpose operation
mat3 = mat2.T
print('A: ', mat1.shape, 'B: ', mat3.shape)

A:  (4, 5) B:  (5, 4)


In [27]:
mat3

array([[0.00578983, 0.25014527, 0.96314436, 0.88965735],
       [0.51070896, 0.08218338, 0.35094065, 0.8589889 ],
       [0.60682532, 0.78042585, 0.17994085, 0.51257492],
       [0.38014173, 0.68079187, 0.52446271, 0.57069585],
       [0.7881372 , 0.32073964, 0.96251401, 0.48683036]])

In [31]:
mm = mat1 @ mat3
mm

array([[1.06422976, 0.98318186, 1.7258127 , 1.80323584],
       [1.02620709, 0.84687738, 1.76195612, 1.91277805],
       [0.37169681, 0.15853848, 0.38530436, 0.67875169],
       [0.59346929, 0.59439356, 0.44876289, 0.69194712]])

In [32]:
mm.shape

(4, 4)

In [34]:
mat1[0], mat3[:,0]

(array([0.63618784, 0.5729108 , 0.12698371, 0.75403451, 0.51292941]),
 array([0.00578983, 0.51070896, 0.60682532, 0.38014173, 0.7881372 ]))

In [37]:
mm00 = mat1[0].dot(mat3[:,0])
print ('This value mm00: {} must be the same as mm[0,0]: {}'.format(mm00, mm[0,0]))

This value mm00: 1.0642297607951565 must be the same as mm[0,0]: 1.0642297607951563


In [39]:
diff = mm00 - mm[0,0]
print ('this means zeros: ', diff)

this means zeros:  2.220446049250313e-16


### 3.3 Matrix - Vector Multiplication

In [46]:
mat1.shape, v1.shape

((4, 5), (5,))

The dimension of $v_1$ must be $5\times1$ for the m-v multiplication

In [58]:
v5x1 = v1[:,np.newaxis]
v5x1

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])

Now we can compute the multiplication as the definition says.

In [61]:
mv_5x1 = mat1 @ v5x1
mv_5x1

array([[7.74374565],
       [7.19122493],
       [1.87204646],
       [3.50230443]])

- `Numpy` just do it without dimension extension. I don't recomment it if you feel confused.

In [63]:
mv1 = mat1 @ v1
mv1

array([7.74374565, 7.19122493, 1.87204646, 3.50230443])

Notice that the two variables `mv_5x1` and `mv1` have the same values, but different dimensions.

In [64]:
mv1.shape, mv_5x1.shape

((4,), (4, 1))

In [67]:
# simple subtraction will result in something unexpected!
mv1 - mv_5x1

array([[ 0.        , -0.55252073, -5.8716992 , -4.24144122],
       [ 0.55252073,  0.        , -5.31917847, -3.6889205 ],
       [ 5.8716992 ,  5.31917847,  0.        ,  1.63025798],
       [ 4.24144122,  3.6889205 , -1.63025798,  0.        ]])

In [69]:
# you can use squeeze
mv_5x1_sqz = mv_5x1.squeeze(axis=1)
mv_5x1_sqz

array([7.74374565, 7.19122493, 1.87204646, 3.50230443])

### 3.4 Matrix Decompositions

In [74]:
mat = np.random.random((4,4))
mat = mat + mat.T # make it symmetric for better understanding
mat

array([[0.0713133 , 1.69201849, 0.48242949, 0.92747879],
       [1.69201849, 1.17420144, 0.15699607, 1.22035258],
       [0.48242949, 0.15699607, 1.04091717, 1.05078492],
       [0.92747879, 1.22035258, 1.05078492, 0.13638052]])

#### Eigen-decomposition

In [83]:
ev, em = np.linalg.eig (mat)
ev

array([ 3.48435121,  1.07770379, -1.21708699, -0.92215559])

In [84]:
recon = em @ np.diag (ev) @ em.T
recon - mat

array([[-2.05391260e-15, -6.66133815e-16, -2.22044605e-16,
        -4.44089210e-16],
       [-8.88178420e-16,  0.00000000e+00,  4.71844785e-16,
         2.22044605e-16],
       [-2.22044605e-16,  5.82867088e-16, -4.44089210e-16,
        -6.66133815e-16],
       [-2.22044605e-16,  4.44089210e-16, -6.66133815e-16,
        -2.22044605e-16]])

#### Singular Value Decomposition (SVD)

In [85]:
u, s, vt = np.linalg.svd(mat)

In [86]:
s

array([3.48435121, 1.21708699, 1.07770379, 0.92215559])

In [87]:
recon = u @ np.diag(s) @ vt
recon - mat

array([[-2.77555756e-17, -8.88178420e-16, -2.22044605e-16,
        -4.44089210e-16],
       [-4.44089210e-16, -2.22044605e-16,  2.22044605e-16,
        -6.66133815e-16],
       [-2.77555756e-16, -1.94289029e-16, -6.66133815e-16,
         0.00000000e+00],
       [ 1.11022302e-16, -4.44089210e-16, -4.44089210e-16,
         2.49800181e-16]])

SVD for a $m\times n$ matrix

In [100]:
mat43 = np.random.random((4,3))
mat43

array([[0.5837292 , 0.84594617, 0.32589844],
       [0.84651713, 0.46787288, 0.34357731],
       [0.62449203, 0.80695352, 0.67992135],
       [0.5456931 , 0.92357129, 0.15904557]])

In [103]:
u, s, vt = np.linalg.svd (mat43, full_matrices=False)

In [104]:
u.shape, s.shape, vt.shape

((4, 3), (3,), (3, 3))

In [105]:
recon = u @ np.diag(s) @ vt
recon - mat43

array([[ 0.00000000e+00, -3.33066907e-16, -1.66533454e-16],
       [ 2.22044605e-16, -2.22044605e-16,  1.66533454e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.11022302e-16],
       [-1.11022302e-16, -1.11022302e-16, -2.22044605e-16]])

In [106]:
u

array([[-0.49960054, -0.27131406, -0.01033542],
       [-0.4501305 ,  0.67727464, -0.57913804],
       [-0.55753374,  0.25153317,  0.75184489],
       [-0.48676273, -0.63593931, -0.31499457]])

In [113]:
# u is a unitary (or orthogonal) matrix: the columns are orthogonal to each other, and mag = 1
u.T @ u

array([[ 1.00000000e+00, -4.79618855e-17,  7.58104736e-17],
       [-4.79618855e-17,  1.00000000e+00, -7.11705519e-17],
       [ 7.58104736e-17, -7.11705519e-17,  1.00000000e+00]])

In [109]:
# but this is not!
u @ u.T

array([[ 0.32331884,  0.04711695,  0.20252905,  0.4189818 ],
       [ 0.04711695,  0.99671927, -0.01410199, -0.02917348],
       [ 0.20252905, -0.01410199,  0.93938354, -0.12540025],
       [ 0.4189818 , -0.02917348, -0.12540025,  0.74057834]])

In [120]:
# vt is a unitary and square matrix
vt.T @ vt

array([[ 1.00000000e+00, -1.49052605e-16,  4.24694880e-17],
       [-1.49052605e-16,  1.00000000e+00, -2.44365700e-16],
       [ 4.24694880e-17, -2.44365700e-16,  1.00000000e+00]])

In [121]:
# so this too results in id. matrix
vt @ vt.T

array([[ 1.00000000e+00, -1.62959673e-16, -3.67352144e-17],
       [-1.62959673e-16,  1.00000000e+00,  2.85891092e-16],
       [-3.67352144e-17,  2.85891092e-16,  1.00000000e+00]])

In [125]:
for i in range(vt.shape[0]):
    print ('mag: ', np.linalg.norm(vt[i]))

mag:  1.0
mag:  1.0000000000000002
mag:  1.0000000000000002


In [126]:
for i in range(vt.T.shape[0]):
    print ('mag: ', np.linalg.norm(vt.T[i]))

mag:  1.0
mag:  1.0
mag:  1.0000000000000004


#### Determinant

In [129]:
np.linalg.det(vt), np.linalg.det(vt.T)

(1.0000000000000004, 1.0000000000000007)

#### Inverse of non-singular square matrix

In [138]:
np.linalg.det( mat ) 

4.214510644309093

In [140]:
inv = np.linalg.inv (mat)
ii = inv @ mat


array([[ 1.00000000e+00,  1.70275839e-16,  1.03878768e-16,
         6.90828037e-17],
       [ 1.36593327e-17,  1.00000000e+00, -9.03953211e-17,
        -1.02775599e-16],
       [ 6.73334169e-18, -6.56488945e-17,  1.00000000e+00,
         2.47696350e-17],
       [ 2.76455308e-17, -1.01139476e-16,  3.75252671e-17,
         1.00000000e+00]])

# END