In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Matrix operation with `numpy`

## 1. definition

In [3]:
dim = 5
rows = 4
cols = 5

## 2. Vector

In [4]:
v1 = np.array([1,2,3,4,5.])
v2 = np.random.random(5)
print ('v1: ', v1, '\nv2: ', v2)

v1:  [1. 2. 3. 4. 5.] 
v2:  [0.77800502 0.11249473 0.85869307 0.86501041 0.65941366]


## 2.1 Element-wise +, -, *, /

In [5]:
v = v1 + v2
v

array([1.77800502, 2.11249473, 3.85869307, 4.86501041, 5.65941366])

In [6]:
v = v1 * v2
v

array([0.77800502, 0.22498946, 2.57607922, 3.46004164, 3.2970683 ])

In [7]:
v = v1 / v2
v

array([ 1.28533874, 17.77861033,  3.49368138,  4.6242218 ,  7.58249381])

### 2.2 dot product

In [8]:
dp = np.dot(v1, v2)
dp

10.336183648399292

In [9]:
dot_sum = 0
for i in range (v1.shape[0]):
    dot_sum += v1[i]*v2[i]
print ('Dot product of two vectors: ', dot_sum, dp, ' and difference: ', dot_sum - dp)

Dot product of two vectors:  10.336183648399292 10.336183648399292  and difference:  0.0


## 3. Matrix

In [10]:
mat1 = np.random.random((rows,cols)) # random in [0, 1)
mat1

array([[0.39871278, 0.55993938, 0.21599858, 0.95166716, 0.8479402 ],
       [0.64693416, 0.06976267, 0.98128062, 0.148482  , 0.93595359],
       [0.95941715, 0.49385142, 0.75317432, 0.29361608, 0.23563149],
       [0.93001901, 0.58493894, 0.61066721, 0.20397832, 0.23291605]])

In [11]:
mat1.shape, mat1.dtype

((4, 5), dtype('float64'))

In [12]:
mat2 = np.random.random((rows, cols))
mat2

array([[0.66474311, 0.84841459, 0.07574252, 0.86351704, 0.59979704],
       [0.69388314, 0.04657993, 0.69162106, 0.91788958, 0.53858954],
       [0.89212153, 0.96263749, 0.63629206, 0.58231023, 0.92114585],
       [0.2979981 , 0.76391106, 0.80053355, 0.85008953, 0.27190003]])

### 3.1 Element-wise Matrix operations: +, -, *, /

In [13]:
m = mat1 + mat2
m

array([[1.06345589, 1.40835397, 0.2917411 , 1.8151842 , 1.44773724],
       [1.3408173 , 0.1163426 , 1.67290168, 1.06637158, 1.47454313],
       [1.85153868, 1.4564889 , 1.38946638, 0.87592631, 1.15677734],
       [1.22801711, 1.34885   , 1.41120076, 1.05406785, 0.50481608]])

In [14]:
m = mat1 * mat2
m

array([[0.26504157, 0.47506074, 0.01636028, 0.82178081, 0.50859202],
       [0.44889671, 0.00324954, 0.67867434, 0.13629008, 0.50409481],
       [0.85591669, 0.47539989, 0.47923884, 0.17097565, 0.21705097],
       [0.2771439 , 0.44684133, 0.48885959, 0.17339984, 0.06332988]])

In [15]:
m = mat1 / mat2
m

array([[0.59979979, 0.6599832 , 2.85174791, 1.10208266, 1.41371188],
       [0.93233877, 1.49769786, 1.41881253, 0.16176455, 1.73778643],
       [1.07543324, 0.5130191 , 1.1836928 , 0.50422621, 0.25580259],
       [3.12088909, 0.76571603, 0.76282525, 0.23994923, 0.85662387]])

### 3.2 Matrix multiplication: @
- size constraint must be satisfied
- $ A(r,c) \times B(c, d) = C(r,d) $

In [16]:
# matrix transpose operation
mat3 = mat2.T
print('A: ', mat1.shape, 'B: ', mat3.shape)

A:  (4, 5) B:  (5, 4)


In [17]:
mat3

array([[0.66474311, 0.69388314, 0.89212153, 0.2979981 ],
       [0.84841459, 0.04657993, 0.96263749, 0.76391106],
       [0.07574252, 0.69162106, 0.63629206, 0.80053355],
       [0.86351704, 0.91788958, 0.58231023, 0.85008953],
       [0.59979704, 0.53858954, 0.92114585, 0.27190003]])

In [18]:
mm = mat1 @ mat3
mm

array([[2.08683542, 1.78234827, 2.36739919, 1.75903089],
       [1.25315628, 1.77120548, 2.21729346, 1.41233448],
       [1.50867757, 1.60605397, 2.19858204, 1.57977253],
       [1.47658905, 1.40759696, 2.11466515, 1.44957453]])

In [19]:
mm.shape

(4, 4)

In [20]:
mat1[0], mat3[:,0]

(array([0.39871278, 0.55993938, 0.21599858, 0.95166716, 0.8479402 ]),
 array([0.66474311, 0.84841459, 0.07574252, 0.86351704, 0.59979704]))

In [21]:
mm00 = mat1[0].dot(mat3[:,0])
print ('This value mm00: {} must be the same as mm[0,0]: {}'.format(mm00, mm[0,0]))

This value mm00: 2.086835422362346 must be the same as mm[0,0]: 2.086835422362346


In [22]:
diff = mm00 - mm[0,0]
print ('this means zeros: ', diff)

this means zeros:  0.0


### 3.3 Matrix - Vector Multiplication

In [23]:
mat1.shape, v1.shape

((4, 5), (5,))

The dimension of $v_1$ must be $5\times1$ for the m-v multiplication

In [24]:
v5x1 = v1[:,np.newaxis]
v5x1

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])

Now we can compute the multiplication as the definition says.

In [25]:
mv_5x1 = mat1 @ v5x1
mv_5x1

array([[10.21295691],
       [ 9.00399728],
       [ 6.55926475],
       [ 5.91239208]])

#### `Numpy` just does it without dimension extension. I don't recomment this way because it is quite confused.

In [26]:
mv1 = mat1 @ v1
mv1

array([10.21295691,  9.00399728,  6.55926475,  5.91239208])

Notice that the two variables `mv_5x1` and `mv1` have the same values, but different dimensions.

In [27]:
mv1.shape, mv_5x1.shape

((4,), (4, 1))

#### Warning!

In [27]:
# simple subtraction will result in something unexpected!
mv1 - mv_5x1

array([[ 0.        ,  6.32898273,  0.52872064,  2.99761278],
       [-6.32898273,  0.        , -5.80026209, -3.33136995],
       [-0.52872064,  5.80026209,  0.        ,  2.46889214],
       [-2.99761278,  3.33136995, -2.46889214,  0.        ]])

#### Warning 2

In [28]:
mv_5x1 - mv1

array([[ 0.        ,  1.20895963,  3.65369217,  4.30056484],
       [-1.20895963,  0.        ,  2.44473254,  3.09160521],
       [-3.65369217, -2.44473254,  0.        ,  0.64687267],
       [-4.30056484, -3.09160521, -0.64687267,  0.        ]])

#### Possibly use `squeez` or `newaxis`

In [30]:
# you can use squeeze
mv_5x1_sqz = mv_5x1.squeeze(axis=1)
mv_5x1_sqz - mv1

array([0., 0., 0., 0.])

## 3.4 Matrix Decompositions

In [31]:
mat = np.random.random((4,4))
mat = mat + mat.T # make it symmetric for better understanding
mat

array([[0.803034  , 1.40063131, 1.4362312 , 0.72150439],
       [1.40063131, 0.334388  , 1.19815513, 0.70397009],
       [1.4362312 , 1.19815513, 1.92772465, 1.16010366],
       [0.72150439, 0.70397009, 1.16010366, 1.45436093]])

### Eigen-decomposition

In [32]:
ev, em = np.linalg.eig (mat)
ev

array([ 4.57925592, -0.85467836,  0.06873724,  0.72619279])

In [33]:
recon = em @ np.diag (ev) @ em.T
recon - mat

array([[-2.44249065e-15, -1.11022302e-15, -1.55431223e-15,
        -1.11022302e-15],
       [-1.11022302e-15, -4.99600361e-16, -4.44089210e-16,
        -3.33066907e-16],
       [-1.33226763e-15, -4.44089210e-16, -4.44089210e-16,
        -2.22044605e-16],
       [-9.99200722e-16, -2.22044605e-16, -2.22044605e-16,
         2.22044605e-16]])

### Singular Value Decomposition (SVD)

In [34]:
u, s, vt = np.linalg.svd(mat)

In [35]:
s

array([4.57925592, 0.85467836, 0.72619279, 0.06873724])

In [36]:
recon = u @ np.diag(s) @ vt
recon - mat

array([[-3.33066907e-16, -4.44089210e-16, -1.55431223e-15,
        -1.11022302e-16],
       [-1.55431223e-15, -1.11022302e-16, -1.55431223e-15,
        -3.33066907e-16],
       [-1.55431223e-15, -2.22044605e-16, -1.55431223e-15,
        -6.66133815e-16],
       [-6.66133815e-16, -1.11022302e-16, -8.88178420e-16,
        -2.22044605e-16]])

#### SVD for a $m\times n$ matrix ($m > n$)

In [37]:
mat43 = np.random.random((4,3))
mat43

array([[0.28268886, 0.59747563, 0.10659661],
       [0.28097661, 0.08493189, 0.04469242],
       [0.13833209, 0.18742583, 0.07919509],
       [0.64213379, 0.08752161, 0.58019476]])

In [36]:
u, s, vt = np.linalg.svd (mat43, full_matrices=False)

In [37]:
u.shape, s.shape, vt.shape

((4, 3), (3,), (3, 3))

In [38]:
recon = u @ np.diag(s) @ vt
recon - mat43

array([[ 1.66533454e-16,  4.44089210e-16,  2.77555756e-17],
       [-1.94289029e-16,  3.33066907e-16,  2.22044605e-16],
       [ 1.11022302e-16, -6.93889390e-18, -5.55111512e-17],
       [ 4.44089210e-16,  1.66533454e-16,  0.00000000e+00]])

In [39]:
u

array([[-0.35683369, -0.33065197,  0.54662544],
       [-0.40758108, -0.76001477, -0.45863378],
       [-0.45973424,  0.47301054, -0.59176398],
       [-0.70369866,  0.2988442 ,  0.37506145]])

In [40]:
# u is a unitary (or orthogonal) matrix: the columns are orthogonal to each other, and mag = 1
u.T @ u

array([[ 1.00000000e+00, -1.29230700e-16, -2.22439025e-16],
       [-1.29230700e-16,  1.00000000e+00,  6.68365100e-17],
       [-2.22439025e-16,  6.68365100e-17,  1.00000000e+00]])

In [41]:
# but this is not!
u @ u.T

array([[ 0.53546038,  0.14603816, -0.31582644,  0.3573081 ],
       [ 0.14603816,  0.95408972,  0.09928693, -0.11232759],
       [-0.31582644,  0.09928693,  0.78527915,  0.24292297],
       [ 0.3573081 , -0.11232759,  0.24292297,  0.72517075]])

In [42]:
# vt is a unitary and square matrix
vt.T @ vt

array([[ 1.00000000e+00, -1.99243502e-16, -2.30716939e-16],
       [-1.99243502e-16,  1.00000000e+00,  2.62264783e-17],
       [-2.30716939e-16,  2.62264783e-17,  1.00000000e+00]])

In [43]:
# so this too results in id. matrix
vt @ vt.T

array([[ 1.00000000e+00,  4.12115070e-17, -1.48279246e-16],
       [ 4.12115070e-17,  1.00000000e+00, -1.81807205e-17],
       [-1.48279246e-16, -1.81807205e-17,  1.00000000e+00]])

In [44]:
for i in range(vt.shape[0]):
    print ('mag: ', np.linalg.norm(vt[i]))

mag:  1.0
mag:  1.0000000000000002
mag:  1.0000000000000002


In [45]:
for i in range(vt.T.shape[0]):
    print ('mag: ', np.linalg.norm(vt.T[i]))

mag:  1.0000000000000002
mag:  1.0000000000000002
mag:  1.0


### Determinant

In [46]:
np.linalg.det(vt), np.linalg.det(vt.T)

(-1.0000000000000007, -1.0000000000000007)

### Inverse of non-singular square matrix

In [39]:
print ('Invertible matrix does have non-zero determinant:', np.linalg.det( mat ) )

Invertible matrix does have non-zero determinant: -0.1953626993849616


#### $A^{-1} \times A = A \times A^{-1} = I$

In [40]:
inv = np.linalg.inv (mat)
ii = inv @ mat
np.linalg.det(ii) # must be 1 since ii is identity matrix

0.9999999999999996

In [41]:
ii

array([[ 1.00000000e+00,  3.33066907e-16, -8.88178420e-16,
        -7.77156117e-16],
       [-1.11022302e-15,  1.00000000e+00, -1.11022302e-15,
        -1.77635684e-15],
       [ 2.22044605e-15, -4.44089210e-16,  1.00000000e+00,
         8.88178420e-16],
       [ 0.00000000e+00, -2.22044605e-16, -2.22044605e-16,
         1.00000000e+00]])

# END